# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3c75745695cf822fb4652022c7a41ce1d4a2acca88ca680e574ea32130245232bb2fa9eaafa050b038209a6c06649c71810256a1eb77a761e20e70c249c3cc7

test:
  secret_key_base: e6d098f5b0dfede8fb439160988633a4ee90edc5717ed44568796fad045fcd0b84ce45628b398e820018a76c5c33da75de8d205a851541621e5a862760107801

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
